### ISSUE TITLE
Klád JSON

### ISSUE THREAD

**Issue by mzsolti84** [mzsolti84/Carnivora#6]
hu.progmatic.klad.KladService -be írtuk meg a JPA-AllKladEntity to Genogram JSON "átfordító" metódust

**Comment by csrzs** [comment]
Elkészítettem a getJsonFromKladEntityList(List<KladEntity> kladEntity funkciót. Kimeneti oldal standard Jsont készít az entitásokból, majd ellátja a szükséges elő- és utó annotációkkal, hogy a genogram be tudja olvasni. A kapott kimenetet DTO-n keresztül tudjuk majd a genogram felé átadni ThymeLeaffel.
